apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hellonuno-dev

namePrefix: dev-

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /metadata/name
        value: hellonuno-dev
    target:
      kind: Namespace

commonLabels:
  environment: development
